### ISSUE TITLE
Doesn't work due to API Key Expiration

### ISSUE THREAD

**Issue by rob-DEV** [evanreilly/youtube-subscriptions-importer#2]
I used my own and it works :)

**Comment by evanreilly** [comment]
Hi rob, thanks for checking this out.  I've been noticing some negative feedback but I haven't had time to diagnose the issue.  I logged into my credential manager and my API key still showed up as valid.  Despite this it was no work to create a new API key and I have since updated both my website and this repository to reflect that.  I have not tested my new key but this is all I have time to do at the moment.
